### ISSUE TITLE
Bigger display

### ISSUE THREAD

**Issue by Vasilis-7** [sfrwmaker/F1-T12-858D#1]
I am thinking that a bigger display will help. In the market there are some economic color or black & white screens using the driver ILI9341. They have resolution up to 240*320 and 2.8"inches. Is it possible to add support for these ?

**Comment by daohuaxiang4** [comment]
Hello! I want to restore the screen to normal display instead of rotating 180°. Which place in the display.cpp file should I modify?

**Comment by sfrwmaker** [comment]
Hello!
I have investigated several displays on the market and you are right, the one based on ili9341 chip is the best choice because of variety of sizes: 2.2", 2.4" and 2.8". Yet it has SPI interface and has acceptable performance. The main problem is design. I am working on it, but still have no idea how to show all the parameters. Perhaps, this display can show the iron and hot gun parameters  simultaneously, but i do not know how.

**Comment by Vasilis-7** [comment]
Thank you for your answer.
A big display is very useful. Because of that, I had started to make the hot air gun with the arduino and the hot iron with the arduino in the same box using 2 arduino mini pro, connected together through serial. The arduino which control the iron will not use its display, instead of that it will send the information by serial to the other arduino. The last one will send all the information on a LCD display 20 x 4.   
But, a bigger display with the features of your project on the STM32 is a great chalenge !!!
I suggest, to use all the display for each unit during setup procedure. The view will be better for the graph. Also if the user is using only one, iron or air gun, you can use all the display with more details or better appearance. If the user wants to use both units, you can split the display horizonticaly with fewer details and simple appearance. 
When the user uses only the hot air gun, you can have a tachometer for measuring the current temperature of the hot air gun, in the center like a odometer, the temperature goal, and beside, a second smaller tachometer like turbo indicator for the blower. When the iron is selected,  you can use something like this https://cdn.mos.cms.futurecdn.net/nvLu9ZnCboT3QeZGjo6NXh-970-80.jpg.
When the user needs both units, you can show him simple numbers with text and colors.
You can use colors to display the temperature grades or bars like an equalizer. The air indicator could be like a round pressure indicator with colors.
You can add a timer that will inform the user, in how many minutes or seconds the unit (iron, air gun or both) will turned off
You can have a graphical menu with buttons, a melody with a screen logo or a beautifull icon at startup.
Perhaps, later,  you can add a touch screen support on it.
Add also a software version view in the setup menu.

Vasilis

**Comment by sfrwmaker** [comment]
Not an issue
