### ISSUE TITLE
The screen problem

### ISSUE THREAD

**Issue by daohuaxiang4** [sfrwmaker/F1-T12-858D#2]
Hello! I want to restore the screen to normal display instead of rotating 180°. Which place in the display.cpp file should I modify?

**Comment by sfrwmaker** [comment]
In the core.cpp, see CFG_STATUS HW::init(void) function.
Change dspl.init(U8G2_R2); to dspl.init(U8G2_R0);

**Comment by sfrwmaker** [comment]
In the core.cpp, see CFG_STATUS HW::init(void) function.
Change dspl.init(U8G2_R2); to dspl.init(U8G2_R0);
