### ISSUE TITLE
hardware reset when gun working

### ISSUE THREAD

**Issue by gyboy** [sfrwmaker/F1-T12-858D#3]
hey, Alexander, I  made one based on your hardware and software .I have changed nothing and it seems work well at the begining,however,when I used the gun for a while,the board automaticlly reset since I haved detected about 10ms low level signal on the reset pin,if I do not use the gun,it seems work well,have you ever met the problem? this IDE is not nice to me and I have problem to debug.

**Comment by sfrwmaker** [comment]
Hello!
No one claimed this issue before.
Can you describe the problem in more detail?
How long it takes before switch-on the hot gun and reset event? I believe many followers use this rework station in hot gun mode for a long time and no one claimed such issue before.
How did you detect the 10ms reset (low ?) signal on reset pin? As far as i know, the reset pin is pulled-up on the bluepill board to 3.3v, yet it does not connected to anything else. Also, no watch-dog timer used in the firmware. So it is hard to imagine what is the issue root. I will investigate this issue.

**Comment by gyboy** [comment]
> 
> 
> Hello!
> No one claimed this issue before.
> Can you describe the problem in more detail?
I just make the station and do not do any calibration before,when I move the gun from the hook , the fan is on and every setting is defalt,(I do not connect thesolder since I just want to check the fan function while the AC zero and relay pin is still work)After about 1min the hardware started reset repetly.I try again today and find that even I remove the gun and just leave the AC zero&delay connect,the station will still reset after about 1min.


> How long it takes before switch-on the hot gun and reset event? I believe many followers use this rework station in hot gun mode for a long time and no one claimed such issue before.
1 min, I forgot to tell you that I just changed 3 pin to fit you T12 project .I modefied GUN_REED_Pin to PA7, ENCODER_R_Pin to PB3 TILT_SW_Pin to PA8 just on main.h since they are just GPIO fuction.Besides,I modified the Encode direction too.

> How did you detect the 10ms reset (low ?) signal on reset pin? As far as i know, the reset pin is pulled-up on the bluepill board to 3.3v, yet it does not connected to anything else. Also, no watch-dog timer used in the firmware. So it is hard to imagine what is the issue root. I will investigate this issue.
I use the oscilloscope and found the low level on reset pin, since my borad has also added the RC delay on reset pin.
besides,when I use the gun menu and select calibration and then push the button to turn on the gun,the sreen will show ERROR after about 6 seconds.

**Comment by sfrwmaker** [comment]
Sorry, I cannot debug modified hardware project. Because i have no such hardware.
You can use debug mode to investigate the issue.

**Comment by gyboy** [comment]
> Sorry, I cannot debug modified hardware project. Because i have no such hardware.
> You can use debug mode to investigate the issue.

Another strange problem is that the gun temp channel which is PA5 keep zero no matter floating or connect to gun, even connected to 3V3,maybe I should resolve this first.

**Comment by gyboy** [comment]
> 
> 
> Sorry, I cannot debug modified hardware project. Because i have no such hardware.
> You can use debug mode to investigate the issue.

hey,bro,I think I have found the problem,but I still have something to enquire you,it looks like the GUN TEMP  ADC doesn't work well even I measured floating voltage on the pin however the buffer can not detect it,I am looking for the problem for futher,maybe other ADC have same problem.I migrate the project to high version,maybe something wrong happened.I want to know have you set the ADC1 and ADC2 global interrupts,since in my cubeMX it is disabled,canyou tell me other settings about ADC too,the pic on the web is not complete,thanks.

**Comment by sfrwmaker** [comment]
Hello!
The controller should be tuned in terms of potentiometers R5 and R19. And to debug the hardware problems, you can use debug mode (called through 'About' menu). Here you can see the raw values the controller reads from the hardware.

**Comment by gyboy** [comment]
> 
> 
> Hello!
> The controller should be tuned in terms of potentiometers R5 and R19. And to debug the hardware problems, you can use debug mode (called through 'About' menu). Here you can see the raw values the controller reads from the hardware.

thanks,I can not go to turn mode now since when I turn on the gun for a while, hard reset will happened.besides, the ADC is still have problem now. I found this problems just on the About menu.I have made you IRON  project before and it works well ,while when I made this station just use same components,problems met on ADC.It seems ADC hardware is simple,but the soft is a little complex,why you set ADC1 and ADC2 to acquire several channels in different interval while use just one adc and continuosly sample 5 channels in one interrupt

**Comment by sfrwmaker** [comment]
Hello!
There is an incorrect call of ADC conversion using DMA in the source code. But it works fine, so i decided to keep this error for a while. Perhaps some day i will release new version where this error will be fixed.
I have tried to change the ADC channels while program work but failed with that so i decided to fix the channels for every measurement. If you check the CubeMX, you can see the ADC1 used to check current through the iron and through fan, gun temperature and ambient temperature. While ADC2 is used to check the iron temperature only. The soldering iron temperature can change quickly so i decided to use average value of 4 temperature samples.

**Comment by gyboy** [comment]
> 
> 
> Hello!
> There is an incorrect call of ADC conversion using DMA in the source code. But it works fine, so i decided to keep this error for a while. Perhaps some day i will release new version where this error will be fixed.
> I have tried to change the ADC channels while program work but failed with that so i decided to fix the channels for every measurement. If you check the CubeMX, you can see the ADC1 used to check current through the iron and through fan, gun temperature and ambient temperature. While ADC2 is used to check the iron temperature only. The soldering iron temperature can change quickly so i decided to use average value of 4 temperature samples.

thanks!
That's the problem ,it seems that all my chips on hand worked not well like yours, I tried to make one same circuit like yours on the bread board,it also doesn't work,the phenomenon is that that gun temp is not update brfore I got in the debug menu,on the main show the gun temp  maintain 25 which is same with NTC ,no matter I connect it to VCC or GND .

I also tried to trance the program,it looked like the "buff[ADC_BUFF_SZ]" catched the right value but updated fail to "gun_temp"
can you describe the error more detaily,I am considering whether I need to use the ADC DMA.

**Comment by sfrwmaker** [comment]
Hello!
First, the hardware issues should be fixed. Check the voltage on pins #3 and pin#1 od AD823 op amp. This is a gun temperature. Also, check the voltage on pin #5 and pin#7 of AD823. This is a iron temperature. Then check the voltage on pin #3 and pin #1 of lm358 this should be the current through the hot air gun fan (when the gun activated) and voltage on pins #5 and #7 - this is a current through the iron. Usually, the hardware is a source of all problems in this project. Sometimes the people buy fake op-amps or other components. Another problem can be fake stm32 board. I have several garbage boards based on cks32 micro controller. They are about compatible with stm32, but does not supported by the development tools.

**Comment by gyboy** [comment]
> 
> 
> Hello!
> First, the hardware issues should be fixed. Check the voltage on pins #3 and pin#1 od AD823 op amp. This is a gun temperature. Also, check the voltage on pin #5 and pin#7 of AD823. This is a iron temperature. Then check the voltage on pin #3 and pin #1 of lm358 this should be the current through the hot air gun fan (when the gun activated) and voltage on pins #5 and #7 - this is a current through the iron. Usually, the hardware is a source of all problems in this project. Sometimes the people buy fake op-amps or other components. Another problem can be fake stm32 board. I have several garbage boards based on cks32 micro controller. They are about compatible with stm32, but does not supported by the development tools.

thanks, I have made sure that the hardware is ok since I have used it on the STM32 T12 project, besides,recently I was studying your code  and tried to do some debug use segger RTT, I disconnect the ADC pin and amp so I can rule out the hardware problem.which means that now the adc pin is float. The result is that the in the "HAL_ADC_ConvCpltCallback" ,I can read the "buff" value and then it should use "core.hotgun.updateTemp(gun_temp);" to update,however ,when I print the "pHG->averageTemp()" in the "MWORK_GUN::loop" function, it stay 0 no matter I turn on the gun or off,but if I go to the "DEBUG" menu,the "pHG->averageTemp()" value will update both in segger RTT and OLED.

**Comment by sfrwmaker** [comment]
What exactly do you see on the debug screen?

**Comment by gyboy** [comment]
> 
> 
> What exactly do you see on the debug screen?

I can see the GUN_TEMP jump from 0 to another value,which means before the value is always zero that I can see from segger RTT directly.

**Comment by gyboy** [comment]
> What exactly do you see on the debug screen?

Hey,man,I have solved the issue.Cause the input signal has too many noise from the gun that the opm can not process the signal.But there is another problem that I need to enquire you,in the eagle project you use MOC3052 to control the AC line, while MOC3052 has non-zero-cross control but the component symbol in your circuit looks like MOC3062 that has zero-cross detect.The problem I met was that when I connent the heat gun,the AC output is zero,if I disconnected the heat load, the output 220V is ok.I measured the head load is about 70ohm that seems to work well,but I do not know why AC output missed.Could you tell which one do you used,3052 or 3062,thks.

**Comment by sfrwmaker** [comment]
Hello!

I used MOC3061 variant. It is not necessary to use zero-cross-detection feature because, there is a zero detector built on 4N25 IC in this project. The know-how is that the Hot Air Gun controller "cuts" whole AC half-period waves starting from zero, then to maximum amplitude and again to zero. The controller detects AC zero crossing time and supplies the power to the MOC3052.
Is the Hot Air Gun Fan rotating? The controller should detect the current through the fan to supply the power the the heater circuit.  To detect the current through the fan, the controller check the voltage drop on R27 resister. Please, check the voltage on pins #3 and #1 of lm358.

**Comment by gyboy** [comment]
> Hello!
> 
> I used MOC3061 variant. It is not necessary to use zero-cross-detection feature because, there is a zero detector built on 4N25 IC in this project. The know-how is that the Hot Air Gun controller "cuts" whole AC half-period waves starting from zero, then to maximum amplitude and again to zero. The controller detects AC zero crossing time and supplies the power to the MOC3052.
> Is the Hot Air Gun Fan rotating? The controller should detect the current through the fan to supply the power the the heater circuit. To detect the current through the fan, the controller check the voltage drop on R27 resister. Please, check the voltage on pins #3 and #1 of lm358.

The fan works well and I can change the speed,maybe I should detect the fan current opm output.I have measured the controller zero cross input and heater output,both looks well as shown below.
![zero detect and power](https://user-images.githubusercontent.com/11901116/106974671-14fcde80-6790-11eb-861c-0f2ae746e27b.jpg)

**Comment by sfrwmaker** [comment]
Hello!
Did you mean voltage on PA11 pin of bluePill board? For sure, the controller is working fine. Please check your TRIAC cirquit.

**Comment by sfrwmaker** [comment]
Fixed
