### ISSUE TITLE
JBC 210 245  iron support

### ISSUE THREAD

**Issue by mojinyinhu** [sfrwmaker/F1-T12-858D#4]
hi，Can you add JBC 210 245 iron core support？

**Comment by sfrwmaker** [comment]
Not planned. Usually universal tool is worse than dedicated one.

**Comment by mojinyinhu** [comment]
936 jbc245 jbc210 these are all 24 V power supply. Under the current circuit, we can detect the resistance value of the heating core of these soldering irons, do automatic detection, and automatically adapt to the maximum power. At present, we see that the general welding platform (supporting 936, T12, JBC) circuit is PWM control scheme, and there are also related products. We hope that we can adapt the software to make the general welding platform, and the power of t12 72w is limited after all, It's not easy to deal with large solder joints. 245 150W power is very good, and the temperature recovery effect is also very good.  hope this scheme can be considered

The attachment is a reference scheme
[Uploading 四合一JBC  T12 936 OLED1.3寸 工作等级焊台资料.zip…]()

**Comment by sfrwmaker** [comment]
Not an issue.
