### ISSUE TITLE
PID control strategy，Temperature overshoot of air gun soldering iron

### ISSUE THREAD

**Issue by mojinyinhu** [sfrwmaker/F1-T12-858D#7]
hello，If it is found that the temperature of the air gun soldering iron is overshoot, can the segmented PID be modified and used: when the temperature difference is >100 ℃, heat at full speed; Radical PID when the temperature difference is 30~100 ℃; Conservative PID when temperature difference <30 ℃;

**Comment by sfrwmaker** [comment]
This strategy does not work.

**Comment by sfrwmaker** [comment]
New firmware manages the soldering iron and hot air gun more accurately.
